### ISSUE TITLE
Does not bypass some AntiCheats

### ISSUE THREAD

**Issue by NidPlays** [DragOP-Menu/DragOP-Menu#5]
Some of the new anticheat currently spawn an invisible npc for detecting aura so make a version where it only hits visible players?

**Comment by ghost** [comment]
Please provide an ip of the Server.

**Comment by NidPlays** [comment]
Play.avengetech.net
Kitpvp Game mode

**Comment by ghost** [comment]
Will be fixed soon.

**Comment by ghost** [comment]
Should be fixed now

**Comment by NidPlays** [comment]
Thanks for adding will test and report back soon

**Comment by NidPlays** [comment]
This issue is not fixed and I still attack an invisible entity
![screenshot_2016-10-22-20-47-35](https://cloud.githubusercontent.com/assets/22031046/19620328/edc8c5a6-9898-11e6-9d49-49523c244cf7.png)

**Comment by ghost** [comment]
Did you download the latest DevVersion?

**Comment by NidPlays** [comment]
Yes it's the latest dev version

**Comment by ghost** [comment]
I'll see what i can do. I think i have a bypass but i cant test it right now.

**Comment by NidPlays** [comment]
Thanks and I can also help with debugging and testing stuff

**Comment by ghost** [comment]
Maybe check if name is null or (I dont think it exists but) Entity.getInvis()?

**Comment by ghost** [comment]
Any idea on how to join the AvengeTech server?

**Comment by NidPlays** [comment]
You can try it on this server 
![screenshot_2016-11-28-13-13-35](https://cloud.githubusercontent.com/assets/22031046/20659912/9e8b5cba-b56c-11e6-8a72-33c64e687f12.png)

**Comment by ghost** [comment]
Ima see

**Comment by nzibn** [comment]
Can you add bypass for leet server and where can i download the latest one?

**Comment by ghost** [comment]
You can download the latest Stable Version here: http://adf.ly/14203551/dragop

**Comment by ghost** [comment]
And which modules dont work on leet?

**Comment by nzibn** [comment]
All of it..i mean when i want to fly..i got kicked out..and when i wanna change gamemode its not changing..and are u sire thats the 1.0.1 version..because it keeps saying thats is 1.0.0 version..

**Comment by ghost** [comment]
Redownload '-'

**Comment by ghost** [comment]
wait a sec

**Comment by ghost** [comment]
https://github.com/DragOP-Menu/DragOP-Menu/releases

**Comment by ghost** [comment]
I used teleport without yMotion and delay = 1.0Seconds. Works like a charm

**Comment by nzibn** [comment]
Which one of bypass I can use to bypass leet anticheat?

**Comment by ghost** [comment]
I would use LBSG
